#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.2.1ubuntu1
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'rnbo-update-service.service' >/dev/null || true
fi
# End automatically added section

# Automatically added by dh_sysuser/UNDECLARED
# -*- sh -*-

CONF_HOME=/nonexistent CONF_PACKAGE=rnbo-update-service CONF_USERNAME=rnbo /lib/sysuser-helper/sysuser-helper prerm "$@"
# End automatically added section
