
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp_____src_UpdateServiceProxyGlue_h__proxy__H__
#define __sdbuscpp_____src_UpdateServiceProxyGlue_h__proxy__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace com {
namespace cycling74 {

class rnbo_proxy
{
public:
    static constexpr const char* INTERFACE_NAME = "com.cycling74.rnbo";

protected:
    rnbo_proxy(sdbus::IProxy& proxy)
        : proxy_(proxy)
    {
    }

    ~rnbo_proxy() = default;

public:
    bool UseLibraryVersion(const std::string& version, const std::vector<std::string>& dependencies)
    {
        bool result;
        proxy_.callMethod("UseLibraryVersion").onInterface(INTERFACE_NAME).withArguments(version, dependencies).storeResultsTo(result);
        return result;
    }

    bool QueueRunnerInstall(const std::string& version)
    {
        bool result;
        proxy_.callMethod("QueueRunnerInstall").onInterface(INTERFACE_NAME).withArguments(version).storeResultsTo(result);
        return result;
    }

    bool QueueInstall(const std::string& packagename, const std::string& version)
    {
        bool result;
        proxy_.callMethod("QueueInstall").onInterface(INTERFACE_NAME).withArguments(packagename, version).storeResultsTo(result);
        return result;
    }

    void UpdateOutdated()
    {
        proxy_.callMethod("UpdateOutdated").onInterface(INTERFACE_NAME);
    }

    void Upgrade()
    {
        proxy_.callMethod("Upgrade").onInterface(INTERFACE_NAME);
    }

public:
    uint32_t State()
    {
        return proxy_.getProperty("State").onInterface(INTERFACE_NAME);
    }

    std::string Status()
    {
        return proxy_.getProperty("Status").onInterface(INTERFACE_NAME);
    }

    uint32_t OutdatedPackages()
    {
        return proxy_.getProperty("OutdatedPackages").onInterface(INTERFACE_NAME);
    }

    std::string LatestRunnerVersion()
    {
        return proxy_.getProperty("LatestRunnerVersion").onInterface(INTERFACE_NAME);
    }

    std::string NewUpdateServiceVersion()
    {
        return proxy_.getProperty("NewUpdateServiceVersion").onInterface(INTERFACE_NAME);
    }

    std::vector<sdbus::Struct<std::string, std::string>> DependencyUpdates()
    {
        return proxy_.getProperty("DependencyUpdates").onInterface(INTERFACE_NAME);
    }

private:
    sdbus::IProxy& proxy_;
};

}} // namespaces

#endif
